<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWpPkGJ6\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWpPkGJ6/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWpPkGJ6.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWpPkGJ6\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWpPkGJ6\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WpPkGJ6',
    'container.build_id' => '333e8ed3',
    'container.build_time' => 1563795453,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWpPkGJ6');
