<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG202UkF\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG202UkF/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG202UkF.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG202UkF\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerG202UkF\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'G202UkF',
    'container.build_id' => '65e112ce',
    'container.build_time' => 1562944040,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG202UkF');
