<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.o2hEQ6e' shared service.

return $this->privates['.service_locator.o2hEQ6e'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'adminPartenaire' => ['privates', '.errored..service_locator.o2hEQ6e.App\\Entity\\AdminPartenaire', NULL, 'Cannot autowire service ".service_locator.o2hEQ6e": it references class "App\\Entity\\AdminPartenaire" but no such service exists.'],
], [
    'adminPartenaire' => 'App\\Entity\\AdminPartenaire',
]);
