<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.DahkhtI' shared service.

return $this->privates['.service_locator.DahkhtI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'adminPartenaireRepository' => ['privates', 'App\\Repository\\AdminPartenaireRepository', 'getAdminPartenaireRepositoryService.php', true],
], [
    'adminPartenaireRepository' => 'App\\Repository\\AdminPartenaireRepository',
]);
