<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSh4Zoa6\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSh4Zoa6/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSh4Zoa6.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSh4Zoa6\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSh4Zoa6\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Sh4Zoa6',
    'container.build_id' => 'b6a1a7df',
    'container.build_time' => 1563924027,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSh4Zoa6');
