<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLH8eMF5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLH8eMF5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLH8eMF5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLH8eMF5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLH8eMF5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LH8eMF5',
    'container.build_id' => '94482a87',
    'container.build_time' => 1563960099,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLH8eMF5');
