<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFH44kV5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFH44kV5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFH44kV5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFH44kV5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFH44kV5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FH44kV5',
    'container.build_id' => '81cecc4a',
    'container.build_time' => 1563966385,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFH44kV5');
