<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.OMVxoJC' shared service.

return $this->privates['.service_locator.OMVxoJC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'adminSystemeRepository' => ['privates', 'App\\Repository\\AdminSystemeRepository', 'getAdminSystemeRepositoryService.php', true],
], [
    'adminSystemeRepository' => 'App\\Repository\\AdminSystemeRepository',
]);
