<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.6b_Qikl' shared service.

return $this->privates['.service_locator.6b_Qikl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AdminPartenaireController::delete' => ['privates', '.service_locator.o2hEQ6e', 'get_ServiceLocator_O2hEQ6eService.php', true],
    'App\\Controller\\AdminPartenaireController::edit' => ['privates', '.service_locator.o2hEQ6e', 'get_ServiceLocator_O2hEQ6eService.php', true],
    'App\\Controller\\AdminPartenaireController::index' => ['privates', '.service_locator.DahkhtI', 'get_ServiceLocator_DahkhtIService.php', true],
    'App\\Controller\\AdminPartenaireController::show' => ['privates', '.service_locator.o2hEQ6e', 'get_ServiceLocator_O2hEQ6eService.php', true],
    'App\\Controller\\AdminSystemeController::delete' => ['privates', '.service_locator.rYDC814', 'get_ServiceLocator_RYDC814Service.php', true],
    'App\\Controller\\AdminSystemeController::edit' => ['privates', '.service_locator.rYDC814', 'get_ServiceLocator_RYDC814Service.php', true],
    'App\\Controller\\AdminSystemeController::index' => ['privates', '.service_locator.OMVxoJC', 'get_ServiceLocator_OMVxoJCService.php', true],
    'App\\Controller\\AdminSystemeController::show' => ['privates', '.service_locator.rYDC814', 'get_ServiceLocator_RYDC814Service.php', true],
    'App\\Controller\\AdminPartenaireController:delete' => ['privates', '.service_locator.o2hEQ6e', 'get_ServiceLocator_O2hEQ6eService.php', true],
    'App\\Controller\\AdminPartenaireController:edit' => ['privates', '.service_locator.o2hEQ6e', 'get_ServiceLocator_O2hEQ6eService.php', true],
    'App\\Controller\\AdminPartenaireController:index' => ['privates', '.service_locator.DahkhtI', 'get_ServiceLocator_DahkhtIService.php', true],
    'App\\Controller\\AdminPartenaireController:show' => ['privates', '.service_locator.o2hEQ6e', 'get_ServiceLocator_O2hEQ6eService.php', true],
    'App\\Controller\\AdminSystemeController:delete' => ['privates', '.service_locator.rYDC814', 'get_ServiceLocator_RYDC814Service.php', true],
    'App\\Controller\\AdminSystemeController:edit' => ['privates', '.service_locator.rYDC814', 'get_ServiceLocator_RYDC814Service.php', true],
    'App\\Controller\\AdminSystemeController:index' => ['privates', '.service_locator.OMVxoJC', 'get_ServiceLocator_OMVxoJCService.php', true],
    'App\\Controller\\AdminSystemeController:show' => ['privates', '.service_locator.rYDC814', 'get_ServiceLocator_RYDC814Service.php', true],
], [
    'App\\Controller\\AdminPartenaireController::delete' => '?',
    'App\\Controller\\AdminPartenaireController::edit' => '?',
    'App\\Controller\\AdminPartenaireController::index' => '?',
    'App\\Controller\\AdminPartenaireController::show' => '?',
    'App\\Controller\\AdminSystemeController::delete' => '?',
    'App\\Controller\\AdminSystemeController::edit' => '?',
    'App\\Controller\\AdminSystemeController::index' => '?',
    'App\\Controller\\AdminSystemeController::show' => '?',
    'App\\Controller\\AdminPartenaireController:delete' => '?',
    'App\\Controller\\AdminPartenaireController:edit' => '?',
    'App\\Controller\\AdminPartenaireController:index' => '?',
    'App\\Controller\\AdminPartenaireController:show' => '?',
    'App\\Controller\\AdminSystemeController:delete' => '?',
    'App\\Controller\\AdminSystemeController:edit' => '?',
    'App\\Controller\\AdminSystemeController:index' => '?',
    'App\\Controller\\AdminSystemeController:show' => '?',
]);
