<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.rYDC814' shared service.

return $this->privates['.service_locator.rYDC814'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'adminSysteme' => ['privates', '.errored..service_locator.rYDC814.App\\Entity\\AdminSysteme', NULL, 'Cannot autowire service ".service_locator.rYDC814": it references class "App\\Entity\\AdminSysteme" but no such service exists.'],
], [
    'adminSysteme' => 'App\\Entity\\AdminSysteme',
]);
