<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Y1LE6Ln' shared service.

return $this->privates['.service_locator.Y1LE6Ln'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\EmployeController::delete' => ['privates', '.service_locator.e69Nya5', 'get_ServiceLocator_E69Nya5Service.php', true],
    'App\\Controller\\EmployeController::edit' => ['privates', '.service_locator.e69Nya5', 'get_ServiceLocator_E69Nya5Service.php', true],
    'App\\Controller\\EmployeController::index' => ['privates', '.service_locator.wvdiBIM', 'get_ServiceLocator_WvdiBIMService.php', true],
    'App\\Controller\\EmployeController::show' => ['privates', '.service_locator.e69Nya5', 'get_ServiceLocator_E69Nya5Service.php', true],
    'App\\Controller\\EmployeController:delete' => ['privates', '.service_locator.e69Nya5', 'get_ServiceLocator_E69Nya5Service.php', true],
    'App\\Controller\\EmployeController:edit' => ['privates', '.service_locator.e69Nya5', 'get_ServiceLocator_E69Nya5Service.php', true],
    'App\\Controller\\EmployeController:index' => ['privates', '.service_locator.wvdiBIM', 'get_ServiceLocator_WvdiBIMService.php', true],
    'App\\Controller\\EmployeController:show' => ['privates', '.service_locator.e69Nya5', 'get_ServiceLocator_E69Nya5Service.php', true],
], [
    'App\\Controller\\EmployeController::delete' => '?',
    'App\\Controller\\EmployeController::edit' => '?',
    'App\\Controller\\EmployeController::index' => '?',
    'App\\Controller\\EmployeController::show' => '?',
    'App\\Controller\\EmployeController:delete' => '?',
    'App\\Controller\\EmployeController:edit' => '?',
    'App\\Controller\\EmployeController:index' => '?',
    'App\\Controller\\EmployeController:show' => '?',
]);
