<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.wvdiBIM' shared service.

return $this->privates['.service_locator.wvdiBIM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'employeRepository' => ['privates', 'App\\Repository\\EmployeRepository', 'getEmployeRepositoryService.php', true],
], [
    'employeRepository' => 'App\\Repository\\EmployeRepository',
]);
