<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Lm7DbpT' shared service.

return $this->privates['.service_locator.Lm7DbpT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\EmployeController::add' => ['privates', '.service_locator.e69Nya5', 'get_ServiceLocator_E69Nya5Service.php', true],
    'App\\Controller\\EmployeController::delete' => ['privates', '.service_locator.e69Nya5', 'get_ServiceLocator_E69Nya5Service.php', true],
    'App\\Controller\\EmployeController:add' => ['privates', '.service_locator.e69Nya5', 'get_ServiceLocator_E69Nya5Service.php', true],
    'App\\Controller\\EmployeController:delete' => ['privates', '.service_locator.e69Nya5', 'get_ServiceLocator_E69Nya5Service.php', true],
], [
    'App\\Controller\\EmployeController::add' => '?',
    'App\\Controller\\EmployeController::delete' => '?',
    'App\\Controller\\EmployeController:add' => '?',
    'App\\Controller\\EmployeController:delete' => '?',
]);
